server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@192.168.217.130:27017
      database: xc_cms
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    addresses: 192.168.217.130
xuecheng:
    mq:
      #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
      queue: queue_cms_postpage_01
      # 站点id
      routingKey: 5a751fab6abb5044e0d19ea1

